# Generated by Django 5.2.10 on 2026-01-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_fitness", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceprofile",
            name="required_room",
        ),
        migrations.RemoveField(
            model_name="serviceprofile",
            name="service",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="ServiceProfile",
        ),
    ]
