# Generated by Django 5.2.10 on 2026-01-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_fitness", "0002_appointmentstatus"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AppointmentStatus",
        ),
    ]
